include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    avoid_redundant_argument_values: true
    sort_constructors_first: true
    prefer_relative_imports: true